# Generated by Django 4.2.7 on 2025-08-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
