# Generated by Django 4.2.7 on 2025-08-04 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_notification_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vertical',
            field=models.CharField(blank=True, choices=[('accessibility', 'Accessibility'), ('climate_change', 'Climate Change'), ('health', 'Health'), ('massom', 'Massom'), ('road_safety', 'Road Safety'), ('sports', 'Sports'), ('entrepreneurship', 'Entrepreneurship'), ('membership', 'Membership'), ('arts_culture', 'Arts & Culture')], max_length=20, null=True),
        ),
    ]
